[phases.setup]
nixPkgs = ["nodejs-18_x", "python39", "pip"]

[phases.install]
cmds = [
    "cd backend && pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build"
]

[start]
cmd = "cd backend && python app.py"

[variables]
PORT = "5000"