services:
  - type: web
    name: youtube-transcript-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production