services:
  - type: web
    name: youtube-transcript-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    
  - type: web
    name: youtube-transcript-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: youtube-transcript-backend
          property: host